### ISSUE TITLE
ACL not serializable for `jobs_runs_submit_and_wait_for_completion`

### ISSUE THREAD

**Issue by avishniakov** [PrefectHQ/prefect-databricks#49]
Hello,

I was trying to set proper ACL for RunSubmit using `jobs_runs_submit_and_wait_for_completion` as follows:
```py
import os
from asyncio import run

from prefect_databricks import DatabricksCredentials
from prefect_databricks.flows import jobs_runs_submit_and_wait_for_completion
from prefect_databricks.models.jobs import (
    AccessControlList,
    AccessControlRequestForGroup,
    AccessControlRequestForUser,
    CanManage,
    CanView,
    NewCluster,
    RunSubmitTaskSettings,
    SparkPythonTask,
)

owners = ["foo@bar.com"]
acl = [
    AccessControlRequestForUser(
        permission_level=CanManage.canmanage,
        user_name=user,
    )
    for user in owners
]
acl.append(
    AccessControlRequestForGroup(group_name="users", permission_level=CanView.canview)
)

run(
    jobs_runs_submit_and_wait_for_completion(
        databricks_credentials=DatabricksCredentials(
            databricks_instance=os.environ["DATABRICKS_INSTANCE"],
            token=os.environ["DATABRICKS_TOKEN"],
        ),
        tasks=[
            RunSubmitTaskSettings(
                new_cluster=NewCluster(
                    spark_version="10.4.x-scala2.12",
                    num_workers=1,
                    node_type_id="m5d.large",
                ),
                spark_python_task=SparkPythonTask(python_file="s3://foo/bar.py"),
                task_key="foo",
            )
        ],
        access_control_list=acl,
    )
)
```

Running it results in following:
```
12:51:21.752 | INFO    | prefect.engine - Created flow run 'space-otter' for flow 'Submit jobs runs and wait for completion'
12:51:22.371 | INFO    | Flow run 'space-otter' - Created task run 'jobs_runs_submit-c00eee75-0' for task 'jobs_runs_submit'
12:51:22.372 | INFO    | Flow run 'space-otter' - Submitted task run 'jobs_runs_submit-c00eee75-0' for execution.
12:51:22.547 | ERROR   | Task run 'jobs_runs_submit-c00eee75-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/***/.venv/lib/python3.8/site-packages/prefect/engine.py", line 1215, in orchestrate_task_run
    result = await task.fn(*args, **kwargs)
  File "/***/.venv/lib/python3.8/site-packages/prefect_databricks/jobs.py", line 1634, in jobs_runs_submit
    response = await execute_endpoint.fn(
  File "/***/.venv/lib/python3.8/site-packages/prefect_databricks/rest.py", line 132, in execute_endpoint
    response = await getattr(client, http_method)(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1520, in request
    request = self.build_request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_client.py", line 360, in build_request
    return Request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_models.py", line 339, in __init__
    headers, stream = encode_request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_content.py", line 211, in encode_request
    return encode_json(json)
  File "/***/.venv/lib/python3.8/site-packages/httpx/_content.py", line 174, in encode_json
    body = json_dumps(json).encode("utf-8")
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CanManage is not JSON serializable
12:51:22.610 | ERROR   | Task run 'jobs_runs_submit-c00eee75-0' - Finished in state Failed('Task run encountered an exception: TypeError: Object of type CanManage is not JSON serializable\n')
12:51:22.610 | ERROR   | Flow run 'space-otter' - Encountered exception during execution:
Traceback (most recent call last):
  File "/***/.venv/lib/python3.8/site-packages/prefect/engine.py", line 603, in orchestrate_flow_run
    result = await flow_call()
  File "/***/.venv/lib/python3.8/site-packages/prefect_databricks/flows.py", line 265, in jobs_runs_submit_and_wait_for_completion
    multi_task_jobs_runs = await multi_task_jobs_runs_future.result()
  File "/***/.venv/lib/python3.8/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/***/.venv/lib/python3.8/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/***/.venv/lib/python3.8/site-packages/prefect/engine.py", line 1215, in orchestrate_task_run
    result = await task.fn(*args, **kwargs)
  File "/***/.venv/lib/python3.8/site-packages/prefect_databricks/jobs.py", line 1634, in jobs_runs_submit
    response = await execute_endpoint.fn(
  File "/***/.venv/lib/python3.8/site-packages/prefect_databricks/rest.py", line 132, in execute_endpoint
    response = await getattr(client, http_method)(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1520, in request
    request = self.build_request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_client.py", line 360, in build_request
    return Request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_models.py", line 339, in __init__
    headers, stream = encode_request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_content.py", line 211, in encode_request
    return encode_json(json)
  File "/***/.venv/lib/python3.8/site-packages/httpx/_content.py", line 174, in encode_json
    body = json_dumps(json).encode("utf-8")
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CanManage is not JSON serializable
12:51:22.670 | ERROR   | Flow run 'space-otter' - Finished in state Failed('Flow run encountered an exception. TypeError: Object of type CanManage is not JSON serializable\n')
Traceback (most recent call last):
  File "tmp/issue.py", line 25, in <module>
    run(
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/***/.venv/lib/python3.8/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/***/.venv/lib/python3.8/site-packages/prefect/engine.py", line 237, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "/***/.venv/lib/python3.8/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/***/.venv/lib/python3.8/site-packages/prefect/engine.py", line 603, in orchestrate_flow_run
    result = await flow_call()
  File "/***/.venv/lib/python3.8/site-packages/prefect_databricks/flows.py", line 265, in jobs_runs_submit_and_wait_for_completion
    multi_task_jobs_runs = await multi_task_jobs_runs_future.result()
  File "/***/.venv/lib/python3.8/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/***/.venv/lib/python3.8/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/***/.venv/lib/python3.8/site-packages/prefect/engine.py", line 1215, in orchestrate_task_run
    result = await task.fn(*args, **kwargs)
  File "/***/.venv/lib/python3.8/site-packages/prefect_databricks/jobs.py", line 1634, in jobs_runs_submit
    response = await execute_endpoint.fn(
  File "/***/.venv/lib/python3.8/site-packages/prefect_databricks/rest.py", line 132, in execute_endpoint
    response = await getattr(client, http_method)(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_client.py", line 1520, in request
    request = self.build_request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_client.py", line 360, in build_request
    return Request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_models.py", line 339, in __init__
    headers, stream = encode_request(
  File "/***/.venv/lib/python3.8/site-packages/httpx/_content.py", line 211, in encode_request
    return encode_json(json)
  File "/***/.venv/lib/python3.8/site-packages/httpx/_content.py", line 174, in encode_json
    body = json_dumps(json).encode("utf-8")
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.8/3.8.15/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CanManage is not JSON serializable
```

Once I remove ACL parameter - request will go to Databricks normally.

I tried to solve serialization issue with modifying parmission level objects like this:
```py
class IsOwner(str, Enum):
    """
    Perimssion that represents ownership of the job.
    """

    isowner = "IS_OWNER"
```
After that request with ACL reach Databricks, but results in `httpx.HTTPStatusError: The request was malformed. See JSON response for error details.JSON response: {'error_code': 'BAD_REQUEST', 'message': 'Principal name not defined'}`

On top of that I tried different definitions of ACLs, like:
```py
acl = [
    AccessControlRequest.parse_obj(
        AccessControlRequestForUser(
            permission_level=CanManage.canmanage,
            user_name=user,
        )
    )
    for user in owners
]
acl.append(
    AccessControlRequest.parse_obj(
        AccessControlRequestForGroup(
            group_name="users", permission_level=CanView.canview
        )
    )
)
```
Also tried keeping only `users` as viewers - same error.

Any advise would be helpful, since this is critical feature: job is normally executed on behalf of automation user.

**Comment by ahuang11** [comment]
What if you only provide it as a string?
```
CanManage.canmanage.value
```


```python
import os
from asyncio import run

from prefect_databricks import DatabricksCredentials
from prefect_databricks.flows import jobs_runs_submit_and_wait_for_completion
from prefect_databricks.models.jobs import (
    AccessControlList,
    AccessControlRequestForGroup,
    AccessControlRequestForUser,
    CanManage,
    CanView,
    NewCluster,
    RunSubmitTaskSettings,
    SparkPythonTask,
)

owners = ["foo@bar.com"]
acl = [
    AccessControlRequestForUser(
        permission_level=CanManage.canmanage.value,
        user_name=user,
    )
    for user in owners
]
acl.append(
    AccessControlRequestForGroup(group_name="users", permission_level=CanView.canview)
)

run(
    jobs_runs_submit_and_wait_for_completion(
        databricks_credentials=DatabricksCredentials(
            databricks_instance=os.environ["DATABRICKS_INSTANCE"],
            token=os.environ["DATABRICKS_TOKEN"],
        ),
        tasks=[
            RunSubmitTaskSettings(
                new_cluster=NewCluster(
                    spark_version="10.4.x-scala2.12",
                    num_workers=1,
                    node_type_id="m5d.large",
                ),
                spark_python_task=SparkPythonTask(python_file="s3://foo/bar.py"),
                task_key="foo",
            )
        ],
        access_control_list=acl,
    )
)

```

**Comment by avishniakov** [comment]
Hey @ahuang11 ,

I tried your options on same snippet:
1. Use `.value` -> `TypeError: Object of type CanManage is not JSON serializable`
ACL list in this case: `[AccessControlRequestForUser(permission_level=PermissionLevel(__root__=<CanManage.canmanage: 'CAN_MANAGE'>), user_name=UserName(__root__='foo@bar.com')), AccessControlRequestForGroup(group_name=GroupName(__root__='users'), permission_level=PermissionLevelForGroup(__root__=<CanView.canview: 'CAN_VIEW'>))]`
2. Use `.json()`
ACL list in this case: `['{"permission_level": "CAN_MANAGE", "user_name": "foo@bar.com"}', '{"group_name": "users", "permission_level": "CAN_VIEW"}']`
```prefect.exceptions.ParameterTypeError: Flow run received invalid parameters:
 - access_control_list: value is not a valid dict
 - access_control_list: value is not a valid dict
 - access_control_list: value is not a valid dict
 - access_control_list: value is not a valid dict```

**Comment by ahuang11** [comment]
Thanks for testing my ideas!

What if you add `json.loads()`
```
import os
import json
from asyncio import run

from prefect_databricks import DatabricksCredentials
from prefect_databricks.flows import jobs_runs_submit_and_wait_for_completion
from prefect_databricks.models.jobs import (
    AccessControlList,
    AccessControlRequestForGroup,
    AccessControlRequestForUser,
    CanManage,
    CanView,
    NewCluster,
    RunSubmitTaskSettings,
    SparkPythonTask,
)

owners = ["foo@bar.com"]
acl = [
    json.loads(
        AccessControlRequestForUser(
            permission_level=CanManage.canmanage.value,
            user_name=user,
        ).json()
    )
    for user in owners
]
acl
```
`[{'permission_level': 'CAN_MANAGE', 'user_name': 'foo@bar.com'}]`

**Comment by avishniakov** [comment]
Hey @ahuang11, unfortunately, same error.
The thing is that whatever you pass into ACL will get transformed after passing into `jobs_runs_submit_and_wait_for_completion`. I'm pretty sure that `@flow` deco is doing that trick and map types strictly.
I added print inside of `jobs_runs_submit_and_wait_for_completion` to showcase it:
```
Before jobs_runs_submit_and_wait_for_completion: [{'permission_level': 'CAN_MANAGE', 'user_name': 'foo@bar.com'}, {'group_name': 'users', 'permission_level': 'CAN_VIEW'}]

Inside jobs_runs_submit_and_wait_for_completion: [AccessControlRequest(__root__=AccessControlRequestForUser(permission_level=PermissionLevel(__root__=<CanManage.canmanage: 'CAN_MANAGE'>), user_name=UserName(__root__='foo@bar.com'))), AccessControlRequest(__root__=AccessControlRequestForUser(permission_level=PermissionLevel(__root__=<CanView.canview: 'CAN_VIEW'>), user_name=None, group_name='users'))]
```

Hope this helps to narrow it down.

**Comment by ahuang11** [comment]
Okay, thanks for explaining! Can you try this:
https://github.com/PrefectHQ/prefect-databricks/pull/50

**Comment by avishniakov** [comment]
Hey @ahuang11 ,

I tried it out - resulted in same error.

I extended this method a bit to illustrate what is inside:
```py
    print(obj, end=": ")
    if isinstance(obj, list):
        return [serialize_model(o) for o in obj]
    elif isinstance(obj, Dict):
        return {k: serialize_model(v) for k, v in obj.items()}

    if isinstance(obj, BaseModel):
        obj = obj.dict()
        print("Serialized as BaseModel\n")
    elif isinstance(obj, Enum):
        obj = obj.value
        print("Serialized as Enum\n")
    else:
        print("Returned plain\n")
    return obj
```

So output is:
```
[RunSubmitTaskSettings(depends_on=None, existing_cluster_id=None, libraries=None, new_cluster=NewCluster(autoscale=None, aws_attributes=None, cluster_log_conf=None, custom_tags=None, driver_instance_pool_id=None, driver_node_type_id=None, enable_elastic_disk=None, init_scripts=None, instance_pool_id=None, node_type_id='m5d.large', num_workers=1, policy_id=None, spark_conf=None, spark_env_vars=None, spark_version='10.4.x-scala2.12', ssh_public_keys=None), notebook_task=None, pipeline_task=None, python_wheel_task=None, spark_jar_task=None, spark_python_task=SparkPythonTask(parameters=None, python_file='s3://foo/bar.py'), spark_submit_task=None, sql_task=None, task_key=TaskKey(__root__='foo'), timeout_seconds=None)]: depends_on=None existing_cluster_id=None libraries=None new_cluster=NewCluster(autoscale=None, aws_attributes=None, cluster_log_conf=None, custom_tags=None, driver_instance_pool_id=None, driver_node_type_id=None, enable_elastic_disk=None, init_scripts=None, instance_pool_id=None, node_type_id='m5d.large', num_workers=1, policy_id=None, spark_conf=None, spark_env_vars=None, spark_version='10.4.x-scala2.12', ssh_public_keys=None) notebook_task=None pipeline_task=None python_wheel_task=None spark_jar_task=None spark_python_task=SparkPythonTask(parameters=None, python_file='s3://foo/bar.py') spark_submit_task=None sql_task=None task_key=TaskKey(__root__='foo') timeout_seconds=None: Serialized as BaseModel

None: Returned plain

None: Returned plain

None: Returned plain

None: Returned plain

[AccessControlRequest(__root__=AccessControlRequestForUser(permission_level=PermissionLevel(__root__=<CanManage.canmanage: 'CAN_MANAGE'>), user_name=UserName(__root__='foo@bar.com'))), AccessControlRequest(__root__=AccessControlRequestForUser(permission_level=PermissionLevel(__root__=<CanView.canview: 'CAN_VIEW'>), user_name=None, group_name='users'))]: __root__=AccessControlRequestForUser(permission_level=PermissionLevel(__root__=<CanManage.canmanage: 'CAN_MANAGE'>), user_name=UserName(__root__='foo@bar.com')): Serialized as BaseModel

__root__=AccessControlRequestForUser(permission_level=PermissionLevel(__root__=<CanView.canview: 'CAN_VIEW'>), user_name=None, group_name='users'): Serialized as BaseModel
```

As you can see it still tries to serialise `AccessControlRequestForUser` as BaseModel using dict, which tries standard `json` logic, afaik.

**Comment by avishniakov** [comment]
I experimented a bit and the issue with `str` based `Enum` can either be solved with `(str, Enum)` definition or adding this to `models/jobs.py`:
```py
_saved_default = JSONEncoder().default


def _new_default(self, obj):
    if isinstance(obj, Enum):
        return obj.value
    else:
        return _saved_default


JSONEncoder.default = _new_default
```

Unfortunately, this still ends with `httpx.HTTPStatusError: The request was malformed. See JSON response for error details.JSON response: {'error_code': 'BAD_REQUEST', 'message': 'Principal name not defined'}`, which is Databricks response.

This is the JSON payload passed into Databricks:
```json
{
    "tasks": [
        {
            "depends_on": None,
            "existing_cluster_id": None,
            "libraries": None,
            "new_cluster": {
                "autoscale": None,
                "aws_attributes": None,
                "cluster_log_conf": None,
                "custom_tags": None,
                "driver_instance_pool_id": None,
                "driver_node_type_id": None,
                "enable_elastic_disk": None,
                "init_scripts": None,
                "instance_pool_id": None,
                "node_type_id": "m5d.large",
                "num_workers": 1,
                "policy_id": None,
                "spark_conf": None,
                "spark_env_vars": None,
                "spark_version": "10.4.x-scala2.12",
                "ssh_public_keys": None
            },
            "notebook_task": None,
            "pipeline_task": None,
            "python_wheel_task": None,
            "spark_jar_task": None,
            "spark_python_task": {
                "parameters": None,
                "python_file": "s3: //foo/bar.py"
            },
            "spark_submit_task": None,
            "sql_task": None,
            "task_key": "foo",
            "timeout_seconds": None
        }
    ],
    "access_control_list": [
        {
            "__root__": {
                "permission_level": <CanManage.canmanage: "CAN_MANAGE">,
                "user_name": "foo@bar.com"
            }
        },
        {
            "__root__": {
                "permission_level": <CanView.canview: "CAN_VIEW">,
                "user_name": None,
                "group_name": "users"
            }
        }
    ]
}
```

My suggestion: rework `AccessControlRequest` like this:
```py
class AccessControlRequest(AccessControlRequestForUser, AccessControlRequestForGroup):
    """
    See source code for the fields' description.
    """

    class Config:
        extra = Extra.allow
        allow_mutation = False
```

After this change the JSOn will look normally:
```json
{
    "tasks": [
        {
            "depends_on": None,
            "existing_cluster_id": None,
            "libraries": None,
            "new_cluster": {
                "autoscale": None,
                "aws_attributes": None,
                "cluster_log_conf": None,
                "custom_tags": None,
                "driver_instance_pool_id": None,
                "driver_node_type_id": None,
                "enable_elastic_disk": None,
                "init_scripts": None,
                "instance_pool_id": None,
                "node_type_id": "m5d.large",
                "num_workers": 1,
                "policy_id": None,
                "spark_conf": None,
                "spark_env_vars": None,
                "spark_version": "10.4.x-scala2.12",
                "ssh_public_keys": None
            },
            "notebook_task": None,
            "pipeline_task": None,
            "python_wheel_task": None,
            "spark_jar_task": None,
            "spark_python_task": {
                "parameters": None,
                "python_file": "s3://foo/bar.py"
            },
            "spark_submit_task": None,
            "sql_task": None,
            "task_key": "foo",
            "timeout_seconds": None
        }
    ],
    "access_control_list": [
        {
            "group_name": None,
            "permission_level": <CanManage.canmanage: "CAN_MANAGE">,
            "user_name": "foo@bar.com"
        },
        {
            "group_name": "users",
            "permission_level": <CanView.canview: "CAN_VIEW">,
            "user_name": None
        }
    ]
}
```

**Comment by avishniakov** [comment]
Unfortunately, I cannot contribute to your PR. Is there any contribution guide?

**Comment by ahuang11** [comment]
Thanks for investigating further; I think you can fork this repo and then make a PR that way.

However, I still see:
```
            "permission_level": <CanManage.canmanage: "CAN_MANAGE">,
```

I think in the future we'll be using another generator and this can be the test case for that:
https://github.com/PrefectHQ/prefect-databricks/pull/36/files

**Comment by avishniakov** [comment]
Cool, raised a PR:https://github.com/PrefectHQ/prefect-databricks/pull/51
